// lib/ghana.ts
// All 16 regions of Ghana with their major cities / towns.
// Used by the physical-copy delivery form (region → city cascading selects).

export type GhanaRegion = {
  name: string;
  capital: string;
  cities: string[];
};

export const GHANA_REGIONS: GhanaRegion[] = [
  {
    name: "Greater Accra",
    capital: "Accra",
    cities: [
      "Accra",
      "Tema",
      "Madina",
      "Adenta",
      "Ashaiman",
      "Teshie",
      "Nungua",
      "Dansoman",
      "Lapaz",
      "Achimota",
      "Spintex",
      "East Legon",
      "Dome",
      "Kasoa (Accra side)",
      "Amasaman",
      "Prampram",
      "Ada Foah",
      "Dodowa",
      "Weija",
      "Sakumono",
    ],
  },
  {
    name: "Ashanti",
    capital: "Kumasi",
    cities: [
      "Kumasi",
      "Obuasi",
      "Ejisu",
      "Konongo",
      "Mampong",
      "Bekwai",
      "Offinso",
      "Asokore Mampong",
      "Tafo",
      "Suame",
      "Asokwa",
      "Kwadaso",
      "Ejura",
      "Agogo",
      "Juaben",
      "Effiduase",
      "Nkawie",
      "Bantama",
    ],
  },
  {
    name: "Western",
    capital: "Sekondi-Takoradi",
    cities: [
      "Takoradi",
      "Sekondi",
      "Tarkwa",
      "Axim",
      "Prestea",
      "Shama",
      "Agona Nkwanta",
      "Half Assini",
      "Elubo",
      "Bogoso",
      "Daboase",
      "Nsuaem",
    ],
  },
  {
    name: "Western North",
    capital: "Sefwi Wiawso",
    cities: [
      "Sefwi Wiawso",
      "Bibiani",
      "Juaboso",
      "Enchi",
      "Bodi",
      "Akontombra",
      "Sefwi Bekwai",
      "Asankragwa",
    ],
  },
  {
    name: "Central",
    capital: "Cape Coast",
    cities: [
      "Cape Coast",
      "Kasoa",
      "Winneba",
      "Mankessim",
      "Swedru",
      "Elmina",
      "Saltpond",
      "Dunkwa-on-Offin",
      "Assin Fosu",
      "Twifo Praso",
      "Apam",
      "Breman Asikuma",
      "Ajumako",
    ],
  },
  {
    name: "Eastern",
    capital: "Koforidua",
    cities: [
      "Koforidua",
      "Nkawkaw",
      "Suhum",
      "Akosombo",
      "Akim Oda",
      "Begoro",
      "Mpraeso",
      "Kibi",
      "Asamankese",
      "Aburi",
      "Nsawam",
      "Akropong",
      "Somanya",
      "Kade",
      "New Tafo",
    ],
  },
  {
    name: "Volta",
    capital: "Ho",
    cities: [
      "Ho",
      "Keta",
      "Aflao",
      "Hohoe",
      "Kpando",
      "Anloga",
      "Sogakope",
      "Denu",
      "Kpetoe",
      "Akatsi",
      "Dzodze",
      "Adidome",
    ],
  },
  {
    name: "Oti",
    capital: "Dambai",
    cities: [
      "Dambai",
      "Jasikan",
      "Kadjebi",
      "Nkwanta",
      "Kete Krachi",
      "Worawora",
      "Chinderi",
      "Brewaniase",
    ],
  },
  {
    name: "Northern",
    capital: "Tamale",
    cities: [
      "Tamale",
      "Yendi",
      "Savelugu",
      "Bimbilla",
      "Gushegu",
      "Tolon",
      "Karaga",
      "Kumbungu",
      "Sang",
      "Zabzugu",
    ],
  },
  {
    name: "Savannah",
    capital: "Damongo",
    cities: [
      "Damongo",
      "Bole",
      "Salaga",
      "Sawla",
      "Buipe",
      "Daboya",
      "Larabanga",
    ],
  },
  {
    name: "North East",
    capital: "Nalerigu",
    cities: [
      "Nalerigu",
      "Walewale",
      "Gambaga",
      "Chereponi",
      "Bunkpurugu",
      "Nakpanduri",
    ],
  },
  {
    name: "Upper East",
    capital: "Bolgatanga",
    cities: [
      "Bolgatanga",
      "Bawku",
      "Navrongo",
      "Zebilla",
      "Paga",
      "Sandema",
      "Bongo",
      "Garu",
    ],
  },
  {
    name: "Upper West",
    capital: "Wa",
    cities: [
      "Wa",
      "Lawra",
      "Jirapa",
      "Nadowli",
      "Tumu",
      "Nandom",
      "Hamile",
      "Funsi",
    ],
  },
  {
    name: "Bono",
    capital: "Sunyani",
    cities: [
      "Sunyani",
      "Berekum",
      "Dormaa Ahenkro",
      "Wenchi",
      "Sampa",
      "Bechem",
      "Nsoatre",
      "Drobo",
    ],
  },
  {
    name: "Bono East",
    capital: "Techiman",
    cities: [
      "Techiman",
      "Kintampo",
      "Nkoranza",
      "Atebubu",
      "Yeji",
      "Kwame Danso",
      "Prang",
      "Jema",
    ],
  },
  {
    name: "Ahafo",
    capital: "Goaso",
    cities: [
      "Goaso",
      "Bechem",
      "Duayaw Nkwanta",
      "Kenyasi",
      "Hwidiem",
      "Kukuom",
      "Mim",
    ],
  },
];

export const GHANA_REGION_NAMES = GHANA_REGIONS.map((r) => r.name);

export function citiesForRegion(region: string): string[] {
  const match = GHANA_REGIONS.find(
    (r) => r.name.toLowerCase() === region.trim().toLowerCase(),
  );
  return match ? match.cities : [];
}
